name: DevOps CI

on:
  push:
    branches:
      - main

jobs:
  pipeline:
      - name: Check logs (threshold)
        run: |
          chmod +x scripts/check_logs_threshold.sh
          ./scripts/check_logs_threshold.sh

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Dar permisos a scripts
        run: chmod +x automation/*.sh

      - name: Ejecutar pipeline
        run: |
          cd automation
          ./pipeline.sh "CI autom√°tico desde GitHub Actions"

